---

- name: Check if Evanti Heat service exists
  win_service:
    name: 'EMSS Agent'
  register: heat_service
  check_mode: true

- debug: var=heat_service

- name: Set fact for Filebeat agent already Installed
  set_fact:
    evantiheat_already_installed: true
  when: heat_service.exists|bool == true

- debug: var=evantiheat_already_installed
